task_tracker_threshold: 0.9
task_tracker_layer: 31
task_tracker_model: "models/trained_linear_probes/phi3/{}/model.pickle"
open_llm_name: "microsoft/Phi-3-mini-4k-instruct"
hf_dir: "disk1/models"
data_path: "mock_data.json"